name: Build Android App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Package Web App to APK
      uses: telerik/progress-apk-builder-action@v1
      with:
        source-dir: '.'
        app-id: 'com.mosesdenzel.musachronicles'
        app-name: 'Musa Chronicles'

    - name: Create GitHub Release and Upload APK
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: ./**/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
